### ISSUE TITLE
Support Sidekiq 7.x

### ISSUE THREAD

**Issue by bobmazanec** [adamniedzielski/sidekiq-staged_push#10]
Sidekiq 7.x removed 6.x's `lib/sidekiq/worker.rb` file, leading to this kind of error:

```
$ rails test
/usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- sidekiq/worker (LoadError)
        from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /usr/local/bundle/gems/sidekiq-staged_push-0.1.0/lib/sidekiq/staged_push.rb:4:in `<main>'
[...]
```

Simply changing `lib/sidekiq/staged_push` to
```
require "sidekiq/worker_compatibility_alias"
```

lets my app tests/examples run, but maybe there's more you'd want to check/do? 🤷

**Comment by adamniedzielski** [comment]
Hey @bobmazanec, thanks for letting me know about this incompatibility. I missed Sidekiq 7 release.

 Adding:

```ruby
require "sidekiq/worker_compatibility_alias"
```

is going to break Sidekiq 6 support, because this file doesn't exist there. What I'd rather do is stop overriding `Sidekiq::Worker.client_push` and instead set `client_class` like here https://github.com/mperham/sidekiq/blob/ad0f13cac5138b891d54ef2f2df3460d5151e34c/lib/sidekiq/transaction_aware_client.rb#L41. This is supported starting from Sidekiq 6.5.0

Feel free to submit a PR in case you're interested.

**Comment by bobmazanec** [comment]
Yah, I didn't know if you'd want one version to support both, or cap 6.x support at 0.1.
Might still want to do something like that, too, if you want to support pre-6.5.0, too.
I'll work up a PR and we can continue the discussion there.

Thanks for the gem & quick response!

**Comment by adamniedzielski** [comment]
Ideally I'd like to release 0.2 that supports >= 6.5.0. I don't consider supporting < 6.5.0 important.

**Comment by adamniedzielski** [comment]
I opened a PR in Sidekiq - https://github.com/mperham/sidekiq/pull/5730. If it gets accepted it will be released in 6.5.9. Still, what I described above is my preference 🙂
